import type { ProjectContent } from './types';

const customTypefaces: ProjectContent = {
  slug:       'custom-typefaces',
  title:      'CUSTOM TYPEFACES',
  resolution: '1440 × 900',
  description:
    'Personal experimental projects. The first chases the warm, rounded nostalgia of 80s design. The second leans into the discomfort of uncertainty with its deliberately unbalanced design.',
  metadata: {
    role: 'Type Designer.',
    categories: ['TYPOGRAPHY', 'TYPE DESIGN'],
    employer: 'PERSONAL',
  },
  sections: [
    { type: 'divider' },

    {
      type:     'typefaceShowcase',
      name:     'REWIND',
      variant:  'rounded',
      letters: [
        { key: 'a',        src: '/images/projects/cystom-typefaces/rounded/a.svg',   alt: 'Letter A' },
        { key: 'b',        src: '/images/projects/cystom-typefaces/rounded/b.svg',   alt: 'Letter B' },
        { key: 'c',        src: '/images/projects/cystom-typefaces/rounded/c.svg',   alt: 'Letter C' },
        { key: 'd',        src: '/images/projects/cystom-typefaces/rounded/d.svg',   alt: 'Letter D' },
        { key: 'e',        src: '/images/projects/cystom-typefaces/rounded/e.svg',   alt: 'Letter E' },
        { key: 'f',        src: '/images/projects/cystom-typefaces/rounded/f.svg',   alt: 'Letter F' },
        { key: 'g',        src: '/images/projects/cystom-typefaces/rounded/g.svg',   alt: 'Letter G' },
        { key: 'h',        src: '/images/projects/cystom-typefaces/rounded/h.svg',   alt: 'Letter H' },
        { key: 'i',        src: '/images/projects/cystom-typefaces/rounded/i.svg',   alt: 'Letter I' },
        { key: 'j',        src: '/images/projects/cystom-typefaces/rounded/j.svg',   alt: 'Letter J' },
        { key: 'k',        src: '/images/projects/cystom-typefaces/rounded/k.svg',   alt: 'Letter K' },
        { key: 'l',        src: '/images/projects/cystom-typefaces/rounded/l.svg',   alt: 'Letter L' },
        { key: 'm',        src: '/images/projects/cystom-typefaces/rounded/m.svg',   alt: 'Letter M' },
        { key: 'n',        src: '/images/projects/cystom-typefaces/rounded/n.svg',   alt: 'Letter N' },
        { key: 'o',        src: '/images/projects/cystom-typefaces/rounded/o.svg',   alt: 'Letter O' },
        { key: 'p',        src: '/images/projects/cystom-typefaces/rounded/p.svg',   alt: 'Letter P' },
        { key: 'q',        src: '/images/projects/cystom-typefaces/rounded/q.svg',   alt: 'Letter Q' },
        { key: 'r',        src: '/images/projects/cystom-typefaces/rounded/r.svg',   alt: 'Letter R' },
        { key: 's',        src: '/images/projects/cystom-typefaces/rounded/s.svg',   alt: 'Letter S' },
        { key: 't',        src: '/images/projects/cystom-typefaces/rounded/t.svg',   alt: 'Letter T' },
        { key: 'u',        src: '/images/projects/cystom-typefaces/rounded/u.svg',   alt: 'Letter U' },
        { key: 'v',        src: '/images/projects/cystom-typefaces/rounded/v.svg',   alt: 'Letter V' },
        { key: 'w',        src: '/images/projects/cystom-typefaces/rounded/w.svg',   alt: 'Letter W' },
        { key: 'x',        src: '/images/projects/cystom-typefaces/rounded/x.svg',   alt: 'Letter X' },
        { key: 'y',        src: '/images/projects/cystom-typefaces/rounded/y.svg',   alt: 'Letter Y' },
        { key: 'z',        src: '/images/projects/cystom-typefaces/rounded/z.svg',   alt: 'Letter Z' },
        { key: 'asterisk', src: '/images/projects/cystom-typefaces/rounded/_.svg',   alt: 'Asterisk glyph' },
      ],
    },

    { type: 'divider' },

    {
      type:     'typefaceShowcase',
      name:     'VERTIGO',
      variant:  'angular',
      letters: [
        { key: 'a',           src: '/images/projects/cystom-typefaces/angular/a.svg',   alt: 'Letter A' },
        { key: 'b',           src: '/images/projects/cystom-typefaces/angular/b.svg',   alt: 'Letter B' },
        { key: 'c',           src: '/images/projects/cystom-typefaces/angular/c.svg',   alt: 'Letter C' },
        { key: 'd',           src: '/images/projects/cystom-typefaces/angular/d.svg',   alt: 'Letter D' },
        { key: 'e',           src: '/images/projects/cystom-typefaces/angular/e.svg',   alt: 'Letter E' },
        { key: 'f',           src: '/images/projects/cystom-typefaces/angular/f.svg',   alt: 'Letter F' },
        { key: 'g',           src: '/images/projects/cystom-typefaces/angular/g.svg',   alt: 'Letter G' },
        { key: 'h',           src: '/images/projects/cystom-typefaces/angular/h.svg',   alt: 'Letter H' },
        { key: 'i',           src: '/images/projects/cystom-typefaces/angular/i.svg',   alt: 'Letter I' },
        { key: 'j',           src: '/images/projects/cystom-typefaces/angular/j.svg',   alt: 'Letter J' },
        { key: 'k',           src: '/images/projects/cystom-typefaces/angular/k.svg',   alt: 'Letter K' },
        { key: 'l',           src: '/images/projects/cystom-typefaces/angular/l.svg',   alt: 'Letter L' },
        { key: 'm',           src: '/images/projects/cystom-typefaces/angular/m.svg',   alt: 'Letter M' },
        { key: 'n',           src: '/images/projects/cystom-typefaces/angular/n.svg',   alt: 'Letter N' },
        { key: 'o',           src: '/images/projects/cystom-typefaces/angular/o.svg',   alt: 'Letter O' },
        { key: 'p',           src: '/images/projects/cystom-typefaces/angular/p.svg',   alt: 'Letter P' },
        { key: 'q',           src: '/images/projects/cystom-typefaces/angular/q.svg',   alt: 'Letter Q' },
        { key: 'r',           src: '/images/projects/cystom-typefaces/angular/r.svg',   alt: 'Letter R' },
        { key: 's',           src: '/images/projects/cystom-typefaces/angular/s.svg',   alt: 'Letter S' },
        { key: 't',           src: '/images/projects/cystom-typefaces/angular/t.svg',   alt: 'Letter T' },
        { key: 'u',           src: '/images/projects/cystom-typefaces/angular/u.svg',   alt: 'Letter U' },
        { key: 'v',           src: '/images/projects/cystom-typefaces/angular/v.svg',   alt: 'Letter V' },
        { key: 'w',           src: '/images/projects/cystom-typefaces/angular/w.svg',   alt: 'Letter W' },
        { key: 'x',           src: '/images/projects/cystom-typefaces/angular/x.svg',   alt: 'Letter X' },
        { key: 'y',           src: '/images/projects/cystom-typefaces/angular/y.svg',   alt: 'Letter Y' },
        { key: 'z',           src: '/images/projects/cystom-typefaces/angular/x-1.svg', alt: 'Letter Z' },
        { key: 'question',    src: '/images/projects/cystom-typefaces/angular/_.svg',   alt: 'Question mark glyph' },
        { key: 'exclamation', src: '/images/projects/cystom-typefaces/angular/!.svg',   alt: 'Exclamation mark' },
      ],
    },

    { type: 'moreProjects' },
  ],
};

export default customTypefaces;
