#!/usr/bin/env python3
"""
A real share card for every project.

── why this exists ───────────────────────────────────────────────────
Project pages pointed `og:image` straight at their hero — a 2640 x 1280
WebP — while declaring it as 1200 x 630. Both halves of that are wrong:

  format   WebP is not reliably rendered as a share card. LinkedIn, which
           is where a portfolio actually gets shared, is the worst of them.
           JPEG is the one format every scraper has always taken.
  size     1200 x 630 is the size Facebook, LinkedIn, Slack, WhatsApp and
           X all agree on, and it was being ASSERTED rather than produced,
           so every scraper was told a dimension no file had.

So each hero is cover-cropped to exactly 1200 x 630 and written as a JPEG.
The crop is centred and takes 2.06:1 down to 1.905:1 — about 70px off each
side of a 2640-wide picture, which no hero composition depends on.

── the stamp is not decoration ───────────────────────────────────────
`next.config.mjs` serves everything under `/images/vol2/` with a one-year
immutable cache. That is only safe because the urls carry a content hash:
replace a hero, regenerate, and the url changes with it. A card written to
a bare filename would be cached by every scraper and CDN for a year and
could never be corrected.

Run after `build-project-assets.mjs`, whenever a hero changes:

    python3 scripts/build-og-cards.py
"""
import hashlib, io, os, re, sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'components/vol2/project/vol2Projects.ts'
OUT_DIR = ROOT / 'public/images/vol2/og'
OUT_TS = ROOT / 'components/vol2/project/ogCards.ts'
W, H = 1200, 630

def sources():
    text = SRC.read_text(encoding='utf-8')
    block = re.search(r'const SOURCES[^\[]*\[(.*?)\n\];', text, re.S).group(1)
    return re.findall(r"\{ slug: '([^']+)', folder: '([^']+)'", block)

def card(hero: Path) -> bytes:
    im = Image.open(hero).convert('RGB')
    # cover: scale so both axes reach the target, then centre-crop
    scale = max(W / im.width, H / im.height)
    im = im.resize((round(im.width * scale), round(im.height * scale)), Image.LANCZOS)
    left, top = (im.width - W) // 2, (im.height - H) // 2
    im = im.crop((left, top, left + W, top + H))
    buf = io.BytesIO()
    # 86 is where this content stops gaining anything visible, and it keeps
    # every card comfortably under the 8MB every platform caps at
    im.save(buf, 'JPEG', quality=86, optimize=True, progressive=True)
    return buf.getvalue()

def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rows, missing = [], []
    for slug, folder in sources():
        hero = ROOT / 'public/images/vol2/projects' / folder / 'hero.webp'
        if not hero.exists():
            missing.append(f'{slug} ({folder})')
            continue
        data = card(hero)
        (OUT_DIR / f'{slug}.jpg').write_bytes(data)
        stamp = hashlib.sha1(data).hexdigest()[:8]
        rows.append((slug, f'/images/vol2/og/{slug}.jpg?v={stamp}', len(data)))

    OUT_TS.write_text(
        '/* GENERATED by scripts/build-og-cards.py — do not edit by hand.\n'
        '   One 1200x630 JPEG share card per project. See the script for why\n'
        '   the hero itself cannot be the card, and why the stamp matters. */\n'
        'export const OG_CARD: Record<string, string> = {\n'
        + ''.join(f'  {slug!r}: {url!r},\n'.replace("'", '"') for slug, url, _ in rows)
        + '};\n',
        encoding='utf-8',
    )

    for slug, url, size in rows:
        print(f'  {slug:22} {size // 1024:>4}KB')
    print(f'{len(rows)} cards -> {OUT_DIR.relative_to(ROOT)}')
    if missing:
        print('NO HERO:', ', '.join(missing), file=sys.stderr)
        return 1
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
