/* GENERATED by scripts/build-project-assets.mjs — do not edit.
   Re-run it after every export from Figma. */

export interface Shot {
  src: string;
  /** real pixel size, so a slot can ask for the shape it wants */
  w: number;
  h: number;
}

/** one loop, in the formats it was encoded to */
export interface Loop {
  webm?: string;
  mp4?: string;
}

export interface ProjectAssets {
  hero: string | null;
  /** `wireframe N`, `image N`, `wide N` — the design's order, shapes mixed */
  stills: Shot[];
  /** full-width feature stills */
  highlights: Shot[];
  /** the feature loops, one entry per loop rather than one per file */
  videos: Loop[];
}

export const ASSETS: Record<string, ProjectAssets> = {
  "BancaSure360": {
    "hero": "/images/vol2/projects/BancaSure360/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/BancaSure360/wireframe%201.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/wireframe%202.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%209.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Benefit Apps": {
    "hero": "/images/vol2/projects/Benefit%20Apps/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Benefit%20Apps/wireframe.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%203.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%209.png",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Cabaret": {
    "hero": "/images/vol2/projects/Cabaret/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Cabaret/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cabaret/image%2010.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [
      {
        "src": "/images/vol2/projects/Cabaret/highlight.png",
        "w": 2640,
        "h": 1280
      }
    ],
    "videos": []
  },
  "Cancellation Insurance": {
    "hero": "/images/vol2/projects/Cancellation%20Insurance/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/wireframe.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%201.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%2010.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Cancellation%20Insurance/Cancellation%20Wallet_highlight%201.mp4",
        "webm": "/images/vol2/projects/Cancellation%20Insurance/Cancellation%20Wallet_highlight%201.webm"
      }
    ]
  },
  "Cybersential": {
    "hero": "/images/vol2/projects/Cybersential/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Cybersential/wireframe.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%201.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%2010.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Czech": {
    "hero": "/images/vol2/projects/Czech/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Czech/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Czech/image%2002.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Czech/image%2003.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "webm": "/images/vol2/projects/Czech/Czech_highlight.webm",
        "mp4": "/images/vol2/projects/Czech/Czech_highlight.mp4"
      }
    ]
  },
  "Danai Michali": {
    "hero": "/images/vol2/projects/Danai%20Michali/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%2010.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [
      {
        "src": "/images/vol2/projects/Danai%20Michali/highlight%201.png",
        "w": 2640,
        "h": 1280
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/highlight%202.png",
        "w": 2640,
        "h": 1280
      }
    ],
    "videos": []
  },
  "Deerislnd": {
    "hero": "/images/vol2/projects/Deerislnd/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Deerislnd/image%201.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%207.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Deerislnd/highlight%201.mp4",
        "webm": "/images/vol2/projects/Deerislnd/highlight%201.webm"
      },
      {
        "mp4": "/images/vol2/projects/Deerislnd/highlight%202.mp4",
        "webm": "/images/vol2/projects/Deerislnd/highlight%202.webm"
      }
    ]
  },
  "Gaspar AI": {
    "hero": "/images/vol2/projects/Gaspar%20AI/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%2010.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%2011.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/wide%2001.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/wide%2002.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/wide%2003.png",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "webm": "/images/vol2/projects/Gaspar%20AI/Gaspar%20AI_highlight.webm",
        "mp4": "/images/vol2/projects/Gaspar%20AI/Gaspar%20AI_highlight.mp4"
      },
      {
        "mp4": "/images/vol2/projects/Gaspar%20AI/gaspar-video-1.mp4",
        "webm": "/images/vol2/projects/Gaspar%20AI/gaspar-video-1.webm"
      },
      {
        "mp4": "/images/vol2/projects/Gaspar%20AI/gaspar-ai-video2.mp4",
        "webm": "/images/vol2/projects/Gaspar%20AI/gaspar-ai-video2.webm"
      }
    ]
  },
  "Mood": {
    "hero": "/images/vol2/projects/Mood/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Mood/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2010.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2011.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2012.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2013.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2014.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2015.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2016.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2017.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2018.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2020.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2021.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Nixteri": {
    "hero": "/images/vol2/projects/Nixteri/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Nixteri/image%2001.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2002.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2003.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2004.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2005.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2006.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2007.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2008.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Olga Posonidou": {
    "hero": "/images/vol2/projects/Olga%20Posonidou/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%201.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%205.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Piraeus Insurance": {
    "hero": "/images/vol2/projects/Piraeus%20Insurance/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/wireframe.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2002.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2003.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2004.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2005.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%207.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%208.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%209.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2010.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2011.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2012.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2013.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Tarrot Cards": {
    "hero": "/images/vol2/projects/Tarrot%20Cards/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2001.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2002.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2003.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2004.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2005.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2006.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2007.png",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/image%2008.png",
        "w": 1600,
        "h": 1600
      }
    ],
    "highlights": [
      {
        "src": "/images/vol2/projects/Tarrot%20Cards/highlight.png",
        "w": 2640,
        "h": 1280
      }
    ],
    "videos": []
  },
  "Typeface A": {
    "hero": "/images/vol2/projects/Typeface%20A/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Typeface%20A/image%201.png",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Typeface%20A/Typeface%20A_highlight%202.mp4",
        "webm": "/images/vol2/projects/Typeface%20A/Typeface%20A_highlight%202.webm"
      }
    ]
  },
  "Typeface b": {
    "hero": "/images/vol2/projects/Typeface%20b/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Typeface%20b/image%201.png",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Vasiliki Vozora": {
    "hero": "/images/vol2/projects/Vasiliki%20Vozora/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/Vasiliki%20Vozora/image%201.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Vasiliki%20Vozora/image%202.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Vasiliki%20Vozora/vozora-03-preview.mp4",
        "webm": "/images/vol2/projects/Vasiliki%20Vozora/vozora-03-preview.webm"
      }
    ]
  },
  "istorima": {
    "hero": "/images/vol2/projects/istorima/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/istorima/image%201.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/Image%202.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%203.png",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%205.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%206.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%207.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "pixel": {
    "hero": "/images/vol2/projects/pixel/hero.png",
    "stills": [
      {
        "src": "/images/vol2/projects/pixel/image%2001.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%2002.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%203.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%204.png",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%205.png",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "webm": "/images/vol2/projects/pixel/pixel_highlight.webm",
        "mp4": "/images/vol2/projects/pixel/pixel_highlight.mp4"
      }
    ]
  }
};
