/* GENERATED by scripts/build-project-assets.mjs — do not edit.
   Re-run it after every export from Figma. */

export interface Shot {
  src: string;
  /** real pixel size, so a slot can ask for the shape it wants */
  w: number;
  h: number;
}

/**
 * The smaller copies of a picture, by its full-size url.
 *
 * A flat map rather than a field on every shot, because the HERO is stored as
 * a bare string in several places (cards, the band, the strip) and it is the
 * one file that most needs a phone-sized version. One lookup serves them all
 * without reshaping anything.
 *
 * Absent means there is nothing smaller — the file is already phone-sized.
 * Nothing is resized at request time, so a width not named here does not
 * exist; see `scripts/build-image-variants.mjs`.
 */
export const SRCSET: Record<string, string> = {
  "/images/vol2/projects/BancaSure360/hero.webp": "/images/vol2/projects/BancaSure360/r/hero-760.webp 760w, /images/vol2/projects/BancaSure360/r/hero-1320.webp 1320w, /images/vol2/projects/BancaSure360/hero.webp 2640w",
  "/images/vol2/projects/BancaSure360/wireframe%201.webp": "/images/vol2/projects/BancaSure360/r/wireframe%201-760.webp 760w, /images/vol2/projects/BancaSure360/r/wireframe%201-1320.webp 1320w, /images/vol2/projects/BancaSure360/wireframe%201.webp 1680w",
  "/images/vol2/projects/BancaSure360/wireframe%202.webp": "/images/vol2/projects/BancaSure360/r/wireframe%202-760.webp 760w, /images/vol2/projects/BancaSure360/r/wireframe%202-1320.webp 1320w, /images/vol2/projects/BancaSure360/wireframe%202.webp 1680w",
  "/images/vol2/projects/Benefit%20Apps/hero.webp": "/images/vol2/projects/Benefit%20Apps/r/hero-760.webp 760w, /images/vol2/projects/Benefit%20Apps/r/hero-1320.webp 1320w, /images/vol2/projects/Benefit%20Apps/hero.webp 2640w",
  "/images/vol2/projects/Benefit%20Apps/wireframe.webp": "/images/vol2/projects/Benefit%20Apps/r/wireframe-760.webp 760w, /images/vol2/projects/Benefit%20Apps/r/wireframe-1320.webp 1320w, /images/vol2/projects/Benefit%20Apps/wireframe.webp 1680w",
  "/images/vol2/projects/Benefit%20Apps/image%203.webp": "/images/vol2/projects/Benefit%20Apps/r/image%203-760.webp 760w, /images/vol2/projects/Benefit%20Apps/r/image%203-1320.webp 1320w, /images/vol2/projects/Benefit%20Apps/image%203.webp 1680w",
  "/images/vol2/projects/Benefit%20Apps/image%209.webp": "/images/vol2/projects/Benefit%20Apps/r/image%209-760.webp 760w, /images/vol2/projects/Benefit%20Apps/r/image%209-1320.webp 1320w, /images/vol2/projects/Benefit%20Apps/image%209.webp 1680w",
  "/images/vol2/projects/Cabaret/hero.webp": "/images/vol2/projects/Cabaret/r/hero-760.webp 760w, /images/vol2/projects/Cabaret/r/hero-1320.webp 1320w, /images/vol2/projects/Cabaret/hero.webp 2640w",
  "/images/vol2/projects/Cabaret/highlight.webp": "/images/vol2/projects/Cabaret/r/highlight-760.webp 760w, /images/vol2/projects/Cabaret/r/highlight-1320.webp 1320w, /images/vol2/projects/Cabaret/highlight.webp 2640w",
  "/images/vol2/projects/Cancellation%20Insurance/hero.webp": "/images/vol2/projects/Cancellation%20Insurance/r/hero-760.webp 760w, /images/vol2/projects/Cancellation%20Insurance/r/hero-1320.webp 1320w, /images/vol2/projects/Cancellation%20Insurance/hero.webp 2640w",
  "/images/vol2/projects/Cancellation%20Insurance/wireframe.webp": "/images/vol2/projects/Cancellation%20Insurance/r/wireframe-760.webp 760w, /images/vol2/projects/Cancellation%20Insurance/r/wireframe-1320.webp 1320w, /images/vol2/projects/Cancellation%20Insurance/wireframe.webp 1680w",
  "/images/vol2/projects/Cybersential/hero.webp": "/images/vol2/projects/Cybersential/r/hero-760.webp 760w, /images/vol2/projects/Cybersential/r/hero-1320.webp 1320w, /images/vol2/projects/Cybersential/hero.webp 2640w",
  "/images/vol2/projects/Cybersential/wireframe.webp": "/images/vol2/projects/Cybersential/r/wireframe-760.webp 760w, /images/vol2/projects/Cybersential/r/wireframe-1320.webp 1320w, /images/vol2/projects/Cybersential/wireframe.webp 1680w",
  "/images/vol2/projects/Czech/hero.webp": "/images/vol2/projects/Czech/r/hero-760.webp 760w, /images/vol2/projects/Czech/r/hero-1320.webp 1320w, /images/vol2/projects/Czech/hero.webp 2640w",
  "/images/vol2/projects/Danai%20Michali/hero.webp": "/images/vol2/projects/Danai%20Michali/r/hero-760.webp 760w, /images/vol2/projects/Danai%20Michali/r/hero-1320.webp 1320w, /images/vol2/projects/Danai%20Michali/hero.webp 2640w",
  "/images/vol2/projects/Danai%20Michali/highlight%201.webp": "/images/vol2/projects/Danai%20Michali/r/highlight%201-760.webp 760w, /images/vol2/projects/Danai%20Michali/r/highlight%201-1320.webp 1320w, /images/vol2/projects/Danai%20Michali/highlight%201.webp 2640w",
  "/images/vol2/projects/Danai%20Michali/highlight%202.webp": "/images/vol2/projects/Danai%20Michali/r/highlight%202-760.webp 760w, /images/vol2/projects/Danai%20Michali/r/highlight%202-1320.webp 1320w, /images/vol2/projects/Danai%20Michali/highlight%202.webp 2640w",
  "/images/vol2/projects/Deerislnd/hero.webp": "/images/vol2/projects/Deerislnd/r/hero-760.webp 760w, /images/vol2/projects/Deerislnd/r/hero-1320.webp 1320w, /images/vol2/projects/Deerislnd/hero.webp 2640w",
  "/images/vol2/projects/Gaspar%20AI/hero.webp": "/images/vol2/projects/Gaspar%20AI/r/hero-760.webp 760w, /images/vol2/projects/Gaspar%20AI/r/hero-1320.webp 1320w, /images/vol2/projects/Gaspar%20AI/hero.webp 2640w",
  "/images/vol2/projects/Gaspar%20AI/wide%2001.webp": "/images/vol2/projects/Gaspar%20AI/r/wide%2001-760.webp 760w, /images/vol2/projects/Gaspar%20AI/r/wide%2001-1320.webp 1320w, /images/vol2/projects/Gaspar%20AI/wide%2001.webp 1680w",
  "/images/vol2/projects/Gaspar%20AI/wide%2002.webp": "/images/vol2/projects/Gaspar%20AI/r/wide%2002-760.webp 760w, /images/vol2/projects/Gaspar%20AI/r/wide%2002-1320.webp 1320w, /images/vol2/projects/Gaspar%20AI/wide%2002.webp 1680w",
  "/images/vol2/projects/Gaspar%20AI/wide%2003.webp": "/images/vol2/projects/Gaspar%20AI/r/wide%2003-760.webp 760w, /images/vol2/projects/Gaspar%20AI/r/wide%2003-1320.webp 1320w, /images/vol2/projects/Gaspar%20AI/wide%2003.webp 1680w",
  "/images/vol2/projects/Mood/hero.webp": "/images/vol2/projects/Mood/r/hero-760.webp 760w, /images/vol2/projects/Mood/r/hero-1320.webp 1320w, /images/vol2/projects/Mood/hero.webp 2640w",
  "/images/vol2/projects/Nixteri/hero.webp": "/images/vol2/projects/Nixteri/r/hero-760.webp 760w, /images/vol2/projects/Nixteri/r/hero-1320.webp 1320w, /images/vol2/projects/Nixteri/hero.webp 2640w",
  "/images/vol2/projects/Nixteri/image%2001.webp": "/images/vol2/projects/Nixteri/r/image%2001-760.webp 760w, /images/vol2/projects/Nixteri/r/image%2001-1320.webp 1320w, /images/vol2/projects/Nixteri/image%2001.webp 1680w",
  "/images/vol2/projects/Olga%20Posonidou/hero.webp": "/images/vol2/projects/Olga%20Posonidou/r/hero-760.webp 760w, /images/vol2/projects/Olga%20Posonidou/r/hero-1320.webp 1320w, /images/vol2/projects/Olga%20Posonidou/hero.webp 2640w",
  "/images/vol2/projects/Olga%20Posonidou/image%201.webp": "/images/vol2/projects/Olga%20Posonidou/r/image%201-760.webp 760w, /images/vol2/projects/Olga%20Posonidou/r/image%201-1320.webp 1320w, /images/vol2/projects/Olga%20Posonidou/image%201.webp 1680w",
  "/images/vol2/projects/Piraeus%20Insurance/hero.webp": "/images/vol2/projects/Piraeus%20Insurance/r/hero-760.webp 760w, /images/vol2/projects/Piraeus%20Insurance/r/hero-1320.webp 1320w, /images/vol2/projects/Piraeus%20Insurance/hero.webp 2640w",
  "/images/vol2/projects/Piraeus%20Insurance/wireframe.webp": "/images/vol2/projects/Piraeus%20Insurance/r/wireframe-760.webp 760w, /images/vol2/projects/Piraeus%20Insurance/r/wireframe-1320.webp 1320w, /images/vol2/projects/Piraeus%20Insurance/wireframe.webp 1680w",
  "/images/vol2/projects/Tarot%20Cards/hero.webp": "/images/vol2/projects/Tarot%20Cards/r/hero-760.webp 760w, /images/vol2/projects/Tarot%20Cards/r/hero-1320.webp 1320w, /images/vol2/projects/Tarot%20Cards/hero.webp 2640w",
  "/images/vol2/projects/Tarot%20Cards/highlight.webp": "/images/vol2/projects/Tarot%20Cards/r/highlight-760.webp 760w, /images/vol2/projects/Tarot%20Cards/r/highlight-1320.webp 1320w, /images/vol2/projects/Tarot%20Cards/highlight.webp 2640w",
  "/images/vol2/projects/Typeface%20A/hero.webp": "/images/vol2/projects/Typeface%20A/r/hero-760.webp 760w, /images/vol2/projects/Typeface%20A/r/hero-1320.webp 1320w, /images/vol2/projects/Typeface%20A/hero.webp 2640w",
  "/images/vol2/projects/Typeface%20A/image%201.webp": "/images/vol2/projects/Typeface%20A/r/image%201-760.webp 760w, /images/vol2/projects/Typeface%20A/r/image%201-1320.webp 1320w, /images/vol2/projects/Typeface%20A/image%201.webp 1680w",
  "/images/vol2/projects/Typeface%20b/hero.webp": "/images/vol2/projects/Typeface%20b/r/hero-760.webp 760w, /images/vol2/projects/Typeface%20b/r/hero-1320.webp 1320w, /images/vol2/projects/Typeface%20b/hero.webp 2640w",
  "/images/vol2/projects/Typeface%20b/image%201.webp": "/images/vol2/projects/Typeface%20b/r/image%201-760.webp 760w, /images/vol2/projects/Typeface%20b/r/image%201-1320.webp 1320w, /images/vol2/projects/Typeface%20b/image%201.webp 1680w",
  "/images/vol2/projects/Vasiliki%20Vozora/hero.webp": "/images/vol2/projects/Vasiliki%20Vozora/r/hero-760.webp 760w, /images/vol2/projects/Vasiliki%20Vozora/r/hero-1320.webp 1320w, /images/vol2/projects/Vasiliki%20Vozora/hero.webp 2640w",
  "/images/vol2/projects/istorima/hero.webp": "/images/vol2/projects/istorima/r/hero-760.webp 760w, /images/vol2/projects/istorima/r/hero-1320.webp 1320w, /images/vol2/projects/istorima/hero.webp 2640w",
  "/images/vol2/projects/istorima/image%203.webp": "/images/vol2/projects/istorima/r/image%203-760.webp 760w, /images/vol2/projects/istorima/r/image%203-1320.webp 1320w, /images/vol2/projects/istorima/image%203.webp 1680w",
  "/images/vol2/projects/pixel/hero.webp": "/images/vol2/projects/pixel/r/hero-760.webp 760w, /images/vol2/projects/pixel/r/hero-1320.webp 1320w, /images/vol2/projects/pixel/hero.webp 2640w"
};

/** the `srcset` for a picture, or undefined when it needs none */
export const srcsetFor = (src: string): string | undefined => SRCSET[src];

/** one loop, in the formats it was encoded to */
export interface Loop {
  webm?: string;
  mp4?: string;
}

export interface ProjectAssets {
  hero: string | null;
  /** `wireframe N`, `image N`, `wide N` — the design's order, shapes mixed */
  stills: Shot[];
  /** full-width feature stills */
  highlights: Shot[];
  /** the feature loops, one entry per loop rather than one per file */
  videos: Loop[];
}

export const ASSETS: Record<string, ProjectAssets> = {
  "BancaSure360": {
    "hero": "/images/vol2/projects/BancaSure360/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/BancaSure360/wireframe%201.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/wireframe%202.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/BancaSure360/image%209.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Benefit Apps": {
    "hero": "/images/vol2/projects/Benefit%20Apps/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Benefit%20Apps/wireframe.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%203.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Benefit%20Apps/image%209.webp",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Cabaret": {
    "hero": "/images/vol2/projects/Cabaret/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Cabaret/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cabaret/image%2010.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [
      {
        "src": "/images/vol2/projects/Cabaret/highlight.webp",
        "w": 2640,
        "h": 1280
      }
    ],
    "videos": []
  },
  "Cancellation Insurance": {
    "hero": "/images/vol2/projects/Cancellation%20Insurance/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/wireframe.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%201.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cancellation%20Insurance/image%2010.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Cancellation%20Insurance/Cancellation%20Wallet_highlight%201.mp4",
        "webm": "/images/vol2/projects/Cancellation%20Insurance/Cancellation%20Wallet_highlight%201.webm"
      }
    ]
  },
  "Cybersential": {
    "hero": "/images/vol2/projects/Cybersential/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Cybersential/wireframe.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%201.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Cybersential/image%2010.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Czech": {
    "hero": "/images/vol2/projects/Czech/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Czech/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Czech/image%2002.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Czech/image%2003.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "webm": "/images/vol2/projects/Czech/Czech_highlight.webm",
        "mp4": "/images/vol2/projects/Czech/Czech_highlight.mp4"
      }
    ]
  },
  "Danai Michali": {
    "hero": "/images/vol2/projects/Danai%20Michali/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/image%2010.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [
      {
        "src": "/images/vol2/projects/Danai%20Michali/highlight%201.webp",
        "w": 2640,
        "h": 1280
      },
      {
        "src": "/images/vol2/projects/Danai%20Michali/highlight%202.webp",
        "w": 2640,
        "h": 1280
      }
    ],
    "videos": []
  },
  "Deerislnd": {
    "hero": "/images/vol2/projects/Deerislnd/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Deerislnd/image%201.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Deerislnd/image%207.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Deerislnd/highlight%201.mp4",
        "webm": "/images/vol2/projects/Deerislnd/highlight%201.webm"
      },
      {
        "mp4": "/images/vol2/projects/Deerislnd/highlight%202.mp4",
        "webm": "/images/vol2/projects/Deerislnd/highlight%202.webm"
      }
    ]
  },
  "Gaspar AI": {
    "hero": "/images/vol2/projects/Gaspar%20AI/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%2010.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/image%2011.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/wide%2001.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/wide%2002.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Gaspar%20AI/wide%2003.webp",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "webm": "/images/vol2/projects/Gaspar%20AI/Gaspar%20AI_highlight.webm",
        "mp4": "/images/vol2/projects/Gaspar%20AI/Gaspar%20AI_highlight.mp4"
      },
      {
        "mp4": "/images/vol2/projects/Gaspar%20AI/gaspar-video-1.mp4",
        "webm": "/images/vol2/projects/Gaspar%20AI/gaspar-video-1.webm"
      },
      {
        "mp4": "/images/vol2/projects/Gaspar%20AI/gaspar-ai-video2.mp4",
        "webm": "/images/vol2/projects/Gaspar%20AI/gaspar-ai-video2.webm"
      }
    ]
  },
  "Mood": {
    "hero": "/images/vol2/projects/Mood/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Mood/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2010.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2011.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2012.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2013.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2014.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2015.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2016.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2017.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2018.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2020.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Mood/image%2021.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Nixteri": {
    "hero": "/images/vol2/projects/Nixteri/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Nixteri/image%2001.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2002.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2003.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2004.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2005.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2006.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2007.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Nixteri/image%2008.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Olga Posonidou": {
    "hero": "/images/vol2/projects/Olga%20Posonidou/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%201.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Olga%20Posonidou/image%205.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Piraeus Insurance": {
    "hero": "/images/vol2/projects/Piraeus%20Insurance/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/wireframe.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2002.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2003.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2004.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2005.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%207.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%208.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%209.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2010.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2011.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2012.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Piraeus%20Insurance/image%2013.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Tarot Cards": {
    "hero": "/images/vol2/projects/Tarot%20Cards/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2001.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2002.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2003.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2004.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2005.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2006.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2007.webp",
        "w": 1600,
        "h": 1600
      },
      {
        "src": "/images/vol2/projects/Tarot%20Cards/image%2008.webp",
        "w": 1600,
        "h": 1600
      }
    ],
    "highlights": [
      {
        "src": "/images/vol2/projects/Tarot%20Cards/highlight.webp",
        "w": 2640,
        "h": 1280
      }
    ],
    "videos": []
  },
  "Typeface A": {
    "hero": "/images/vol2/projects/Typeface%20A/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Typeface%20A/image%201.webp",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Typeface%20A/Typeface%20A_highlight%202.mp4",
        "webm": "/images/vol2/projects/Typeface%20A/Typeface%20A_highlight%202.webm"
      }
    ]
  },
  "Typeface b": {
    "hero": "/images/vol2/projects/Typeface%20b/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Typeface%20b/image%201.webp",
        "w": 1680,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "Vasiliki Vozora": {
    "hero": "/images/vol2/projects/Vasiliki%20Vozora/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/Vasiliki%20Vozora/image%201.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/Vasiliki%20Vozora/image%202.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "mp4": "/images/vol2/projects/Vasiliki%20Vozora/vozora-03-preview.mp4",
        "webm": "/images/vol2/projects/Vasiliki%20Vozora/vozora-03-preview.webm"
      }
    ]
  },
  "istorima": {
    "hero": "/images/vol2/projects/istorima/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/istorima/image%201.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/Image%202.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%203.webp",
        "w": 1680,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%205.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%206.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/istorima/image%207.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": []
  },
  "pixel": {
    "hero": "/images/vol2/projects/pixel/hero.webp",
    "stills": [
      {
        "src": "/images/vol2/projects/pixel/image%2001.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%2002.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%203.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%204.webp",
        "w": 800,
        "h": 800
      },
      {
        "src": "/images/vol2/projects/pixel/image%205.webp",
        "w": 800,
        "h": 800
      }
    ],
    "highlights": [],
    "videos": [
      {
        "webm": "/images/vol2/projects/pixel/pixel_highlight.webm",
        "mp4": "/images/vol2/projects/pixel/pixel_highlight.mp4"
      }
    ]
  }
};
