/* GENERATED by scripts/build-project-assets.mjs — do not edit.
   Re-run it after every export from Figma. */

export interface ProjectAssets {
  hero: string | null;
  /** grid stills, in export order */
  stills: string[];
  /** row-width stills (the wireframes) */
  wides: string[];
  /** full-width feature stills */
  highlights: string[];
  /** full-width feature loops — WebM first where both exist */
  videos: string[];
}

export const ASSETS: Record<string, ProjectAssets> = {
  "BancaSure360": {
    "hero": "/images/vol2/projects/BancaSure360/hero.png",
    "stills": [
      "/images/vol2/projects/BancaSure360/image%2001.png",
      "/images/vol2/projects/BancaSure360/image%202.png",
      "/images/vol2/projects/BancaSure360/image%203.png",
      "/images/vol2/projects/BancaSure360/image%204.png",
      "/images/vol2/projects/BancaSure360/image%205.png",
      "/images/vol2/projects/BancaSure360/image%206.png",
      "/images/vol2/projects/BancaSure360/image%207.png",
      "/images/vol2/projects/BancaSure360/image%208.png",
      "/images/vol2/projects/BancaSure360/image%209.png"
    ],
    "wides": [
      "/images/vol2/projects/BancaSure360/wireframe%201.png",
      "/images/vol2/projects/BancaSure360/wireframe%202.png"
    ],
    "highlights": [],
    "videos": []
  },
  "Benefit Apps": {
    "hero": "/images/vol2/projects/Benefit%20Apps/hero.png",
    "stills": [
      "/images/vol2/projects/Benefit%20Apps/image%2001.png",
      "/images/vol2/projects/Benefit%20Apps/image%202.png",
      "/images/vol2/projects/Benefit%20Apps/image%203.png",
      "/images/vol2/projects/Benefit%20Apps/image%204.png",
      "/images/vol2/projects/Benefit%20Apps/image%205.png",
      "/images/vol2/projects/Benefit%20Apps/image%206.png",
      "/images/vol2/projects/Benefit%20Apps/image%207.png",
      "/images/vol2/projects/Benefit%20Apps/image%208.png",
      "/images/vol2/projects/Benefit%20Apps/image%209.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": []
  },
  "Cabaret": {
    "hero": "/images/vol2/projects/Cabaret/hero.png",
    "stills": [
      "/images/vol2/projects/Cabaret/image%209.png",
      "/images/vol2/projects/Cabaret/image%2010.png"
    ],
    "wides": [],
    "highlights": [
      "/images/vol2/projects/Cabaret/highlight.png"
    ],
    "videos": []
  },
  "Cancellation Insurance": {
    "hero": "/images/vol2/projects/Cancellation%20Insurance/hero.png",
    "stills": [
      "/images/vol2/projects/Cancellation%20Insurance/image%201.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%202.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%203.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%204.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%205.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%206.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%207.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%208.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%209.png",
      "/images/vol2/projects/Cancellation%20Insurance/image%2010.png"
    ],
    "wides": [
      "/images/vol2/projects/Cancellation%20Insurance/wireframe.png"
    ],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/Cancellation%20Insurance/Cancellation%20Wallet_highlight%201.webm"
    ]
  },
  "Cybersential": {
    "hero": "/images/vol2/projects/Cybersential/hero.png",
    "stills": [
      "/images/vol2/projects/Cybersential/image%201.png",
      "/images/vol2/projects/Cybersential/image%202.png",
      "/images/vol2/projects/Cybersential/image%203.png",
      "/images/vol2/projects/Cybersential/image%204.png",
      "/images/vol2/projects/Cybersential/image%205.png",
      "/images/vol2/projects/Cybersential/image%206.png",
      "/images/vol2/projects/Cybersential/image%207.png",
      "/images/vol2/projects/Cybersential/image%208.png",
      "/images/vol2/projects/Cybersential/image%209.png",
      "/images/vol2/projects/Cybersential/image%2010.png"
    ],
    "wides": [
      "/images/vol2/projects/Cybersential/wireframe.png"
    ],
    "highlights": [],
    "videos": []
  },
  "Czech": {
    "hero": "/images/vol2/projects/Czech/hero.png",
    "stills": [
      "/images/vol2/projects/Czech/image%2001.png",
      "/images/vol2/projects/Czech/image%2002.png",
      "/images/vol2/projects/Czech/image%2003.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/Czech/Czech_highlight.webm"
    ]
  },
  "Danai Michali": {
    "hero": "/images/vol2/projects/Danai%20Michali/hero.png",
    "stills": [
      "/images/vol2/projects/Danai%20Michali/image%2001.png",
      "/images/vol2/projects/Danai%20Michali/image%202.png",
      "/images/vol2/projects/Danai%20Michali/image%203.png",
      "/images/vol2/projects/Danai%20Michali/image%204.png",
      "/images/vol2/projects/Danai%20Michali/image%205.png",
      "/images/vol2/projects/Danai%20Michali/image%206.png",
      "/images/vol2/projects/Danai%20Michali/image%207.png",
      "/images/vol2/projects/Danai%20Michali/image%208.png",
      "/images/vol2/projects/Danai%20Michali/image%209.png",
      "/images/vol2/projects/Danai%20Michali/image%2010.png"
    ],
    "wides": [],
    "highlights": [
      "/images/vol2/projects/Danai%20Michali/highlight%201.png",
      "/images/vol2/projects/Danai%20Michali/highlight%202.png"
    ],
    "videos": []
  },
  "Deerislnd": {
    "hero": "/images/vol2/projects/Deerislnd/hero.png",
    "stills": [
      "/images/vol2/projects/Deerislnd/image%201.png",
      "/images/vol2/projects/Deerislnd/image%202.png",
      "/images/vol2/projects/Deerislnd/image%203.png",
      "/images/vol2/projects/Deerislnd/image%204.png",
      "/images/vol2/projects/Deerislnd/image%205.png",
      "/images/vol2/projects/Deerislnd/image%206.png",
      "/images/vol2/projects/Deerislnd/image%207.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/Deerislnd/highlight%201.webm",
      "/images/vol2/projects/Deerislnd/highlight%202.webm"
    ]
  },
  "Gaspar AI": {
    "hero": "/images/vol2/projects/Gaspar%20AI/hero.png",
    "stills": [
      "/images/vol2/projects/Gaspar%20AI/image%2001.png",
      "/images/vol2/projects/Gaspar%20AI/image%202.png",
      "/images/vol2/projects/Gaspar%20AI/image%203.png",
      "/images/vol2/projects/Gaspar%20AI/image%204.png",
      "/images/vol2/projects/Gaspar%20AI/image%205.png",
      "/images/vol2/projects/Gaspar%20AI/image%206.png",
      "/images/vol2/projects/Gaspar%20AI/image%207.png",
      "/images/vol2/projects/Gaspar%20AI/image%208.png",
      "/images/vol2/projects/Gaspar%20AI/image%209.png",
      "/images/vol2/projects/Gaspar%20AI/image%2010.png",
      "/images/vol2/projects/Gaspar%20AI/image%2011.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/Gaspar%20AI/Gaspar%20AI_highlight.webm",
      "/images/vol2/projects/Gaspar%20AI/gaspar-video-1.mp4",
      "/images/vol2/projects/Gaspar%20AI/gaspar-ai-video2.mp4"
    ]
  },
  "Mood": {
    "hero": "/images/vol2/projects/Mood/hero.png",
    "stills": [
      "/images/vol2/projects/Mood/image%2001.png",
      "/images/vol2/projects/Mood/image%202.png",
      "/images/vol2/projects/Mood/image%203.png",
      "/images/vol2/projects/Mood/image%204.png",
      "/images/vol2/projects/Mood/image%205.png",
      "/images/vol2/projects/Mood/image%206.png",
      "/images/vol2/projects/Mood/image%207.png",
      "/images/vol2/projects/Mood/image%208.png",
      "/images/vol2/projects/Mood/image%209.png",
      "/images/vol2/projects/Mood/image%2010.png",
      "/images/vol2/projects/Mood/image%2011.png",
      "/images/vol2/projects/Mood/image%2012.png",
      "/images/vol2/projects/Mood/image%2013.png",
      "/images/vol2/projects/Mood/image%2014.png",
      "/images/vol2/projects/Mood/image%2015.png",
      "/images/vol2/projects/Mood/image%2016.png",
      "/images/vol2/projects/Mood/image%2017.png",
      "/images/vol2/projects/Mood/image%2018.png",
      "/images/vol2/projects/Mood/image%2020.png",
      "/images/vol2/projects/Mood/image%2021.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": []
  },
  "Nixteri": {
    "hero": "/images/vol2/projects/Nixteri/hero.png",
    "stills": [
      "/images/vol2/projects/Nixteri/image%2001.png",
      "/images/vol2/projects/Nixteri/image%2002.png",
      "/images/vol2/projects/Nixteri/image%2003.png",
      "/images/vol2/projects/Nixteri/image%2004.png",
      "/images/vol2/projects/Nixteri/image%2005.png",
      "/images/vol2/projects/Nixteri/image%2006.png",
      "/images/vol2/projects/Nixteri/image%2007.png",
      "/images/vol2/projects/Nixteri/image%2008.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": []
  },
  "Olga Posonidou": {
    "hero": "/images/vol2/projects/Olga%20Posonidou/hero.png",
    "stills": [
      "/images/vol2/projects/Olga%20Posonidou/image%201.png",
      "/images/vol2/projects/Olga%20Posonidou/image%202.png",
      "/images/vol2/projects/Olga%20Posonidou/image%203.png",
      "/images/vol2/projects/Olga%20Posonidou/image%204.png",
      "/images/vol2/projects/Olga%20Posonidou/image%205.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": []
  },
  "Piraeus Insurance": {
    "hero": "/images/vol2/projects/Piraeus%20Insurance/hero.png",
    "stills": [
      "/images/vol2/projects/Piraeus%20Insurance/image%2001.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2002.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2003.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2004.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2005.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%206.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%207.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%208.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%209.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2010.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2011.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2012.png",
      "/images/vol2/projects/Piraeus%20Insurance/image%2013.png"
    ],
    "wides": [
      "/images/vol2/projects/Piraeus%20Insurance/wireframe.png"
    ],
    "highlights": [],
    "videos": []
  },
  "Tarrot Cards": {
    "hero": "/images/vol2/projects/Tarrot%20Cards/hero.png",
    "stills": [
      "/images/vol2/projects/Tarrot%20Cards/image%2001.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2002.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2003.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2004.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2005.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2006.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2007.png",
      "/images/vol2/projects/Tarrot%20Cards/image%2008.png"
    ],
    "wides": [],
    "highlights": [
      "/images/vol2/projects/Tarrot%20Cards/highlight.png"
    ],
    "videos": []
  },
  "Typeface A": {
    "hero": "/images/vol2/projects/Typeface%20A/hero.png",
    "stills": [
      "/images/vol2/projects/Typeface%20A/image%201.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/Typeface%20A/Typeface%20A_highlight%202.webm"
    ]
  },
  "Typeface b": {
    "hero": "/images/vol2/projects/Typeface%20b/hero.png",
    "stills": [
      "/images/vol2/projects/Typeface%20b/image%201.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": []
  },
  "Vasiliki Vozora": {
    "hero": "/images/vol2/projects/Vasiliki%20Vozora/hero.png",
    "stills": [
      "/images/vol2/projects/Vasiliki%20Vozora/image%201.png",
      "/images/vol2/projects/Vasiliki%20Vozora/image%202.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/Vasiliki%20Vozora/vozora-03-preview.mp4"
    ]
  },
  "istorima": {
    "hero": "/images/vol2/projects/istorima/hero.png",
    "stills": [
      "/images/vol2/projects/istorima/image%201.png",
      "/images/vol2/projects/istorima/Image%202.png",
      "/images/vol2/projects/istorima/image%203.png",
      "/images/vol2/projects/istorima/image%204.png",
      "/images/vol2/projects/istorima/image%205.png",
      "/images/vol2/projects/istorima/image%206.png",
      "/images/vol2/projects/istorima/image%207.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": []
  },
  "pixel": {
    "hero": "/images/vol2/projects/pixel/hero.png",
    "stills": [
      "/images/vol2/projects/pixel/image%2001.png",
      "/images/vol2/projects/pixel/image%2002.png",
      "/images/vol2/projects/pixel/image%203.png",
      "/images/vol2/projects/pixel/image%204.png",
      "/images/vol2/projects/pixel/image%205.png"
    ],
    "wides": [],
    "highlights": [],
    "videos": [
      "/images/vol2/projects/pixel/pixel_highlight.webm"
    ]
  }
};
