/* GENERATED by scripts/build-og-cards.py — do not edit by hand.
   One 1200x630 JPEG share card per project. See the script for why
   the hero itself cannot be the card, and why the stamp matters. */
export const OG_CARD: Record<string, string> = {
  "deerislnd": "/images/vol2/og/deerislnd.jpg?v=73f5cf12",
  "cancellation-wallet": "/images/vol2/og/cancellation-wallet.jpg?v=699c5748",
  "cybersential": "/images/vol2/og/cybersential.jpg?v=dd95d96f",
  "piraeus-insurance": "/images/vol2/og/piraeus-insurance.jpg?v=85df4a66",
  "bancasure360": "/images/vol2/og/bancasure360.jpg?v=e364a314",
  "gaspar-ai": "/images/vol2/og/gaspar-ai.jpg?v=7aebe157",
  "mood": "/images/vol2/og/mood.jpg?v=9f331758",
  "istorima": "/images/vol2/og/istorima.jpg?v=4f6f0aa9",
  "benefit": "/images/vol2/og/benefit.jpg?v=b49d9083",
  "book-cover": "/images/vol2/og/book-cover.jpg?v=3d420b42",
  "olga-posonidou": "/images/vol2/og/olga-posonidou.jpg?v=c8ecacf6",
  "vasiliki-vozora": "/images/vol2/og/vasiliki-vozora.jpg?v=d878123f",
  "danai-michali": "/images/vol2/og/danai-michali.jpg?v=e4c05031",
  "arcana": "/images/vol2/og/arcana.jpg?v=0fe4b7f0",
  "cabaret": "/images/vol2/og/cabaret.jpg?v=3f304741",
  "czech-image": "/images/vol2/og/czech-image.jpg?v=1dddcf12",
  "in-pixels-we-see": "/images/vol2/og/in-pixels-we-see.jpg?v=fbbfcb07",
  "angular-typeface": "/images/vol2/og/angular-typeface.jpg?v=ddb3e530",
  "rounded-typeface": "/images/vol2/og/rounded-typeface.jpg?v=6a00ac15",
};
